[package]
name = "rsmixer"
version = "0.2.0"
authors = ["Jan Wojcicki <janwojcicki45@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libpulse-binding = "2.16.0"
simple-logging = "2.0.2"
env_logger = "0.7.1"
log = "0.4.8"
lazy_static = "1.4.0"
unicode-width = "0.1.8"
crossterm = { version = "0.17.5", features = ["serde", "event-stream"] }
tokio = { version = "0.2.21", features = ["full"] }
state = { version = "0.4.1", features = ["tls"] }
toml = "0.5.6"
thiserror = "1.0.20"
futures = "0.3.5"
send_wrapper = "0.4.0"
crossbeam-channel = "0.4.2"
confy = "0.4.0"
serde = { version = "1.0.114", features = ["derive"] }

#[profile.release]
#debug = true
