[package]
name = "rsmixer"
version = "0.1.0"
authors = ["Jan Wojcicki <janwojcicki45@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libpulse-binding = "2.16.0"
simple-logging = "2.0.2"
env_logger = "0.7.1"
log = "0.4.8"
lazy_static = "1.4.0"
unicode-width = "0.1.7"
crossterm = { version = "0.17.5", features = ["event-stream"] }
async-std = { version = "1.6.0", features = ["unstable"] }
state = { version = "0.4.1", features = ["tls", "const_fn"] }
toml = "0.5.6"
thiserror = "*"

[profile.release]
debug = true
